### ISSUE TITLE
qbjs is crashing when I press run

### ISSUE THREAD

**Issue by hacker64-pixel** [boxgaming/qbjs#25]
My browser start to slowly freeze and then crash when I press run
log:
`Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:39203
Feature Policy: Skipping unsupported feature name “autoplay”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “midi”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “monetization”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “gyroscope”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “accelerometer”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “xr”. lib.js:2:50992
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. lib.js:2:50992
Unable to check top-level optout: Permission denied to access property "document" on cross-origin object content.js:1:1564
unreachable code after return statement`

**Comment by boxgaming** [comment]
Hi, thanks for reporting the problem.  Can you submit the source code that caused the issue?

**Comment by hacker64-pixel** [comment]
Here is code:
`Const green = _RGB32(0, 127, 0)
Const brightgreen = _RGB32(0, 255, 0)

Dim KeyPress$
Dim x%, y%

Screen _NewImage(640, 480, 32)
x% = 319
y% = 239
          _TITLE "Leteci krug"
Do
    Cls
    Locate 2, 25
    Print "Koristi WASD da mices krug"
    Locate 29, 27
    Print "pretisni ESC da izades"
    Circle (x%, y%), 50, brightgreen
    Paint (x%, y%), green, brightgreen
    KeyPress$ = InKey$
    If KeyPress$ = "w" Then y% = y% - 1
    If KeyPress$ = "s" Then y% = y% + 1
    If KeyPress$ = "a" Then x% = x% - 1
    If KeyPress$ = "d" Then x% = x% + 1
    _Display
Loop Until KeyPress$ = Chr$(27)`

**Comment by boxgaming** [comment]
This has been resolved in the latest 0.5.0 release.  The code above will no longer cause the browser to lock up.  I would recommend putting a "_Limit 60" before the Loop statement to improve overall performance.
